### ISSUE TITLE
Severe memory leak—caused by Python instance on version 5.0.0 beta—leads to heavy performance loss and game crash

### ISSUE THREAD

**Issue by Tinh1000000** [derekhe/msfs2020-map-enhancement#128]
On the version 5,0.0 beta release, there is a severe memory leak with the Python instance. I recently installed the update from the flightsim.to website and upon loading the program with the simulator, the Python instance's memory usage went skyrocketing.

This issue has caused the simulator to suffer heavy performance losses (via stuttering) and eventually crash the program due to an out-of-memory error. The leak will always occur regardless of how I start the newest version of the program.

**Comment by derekhe** [comment]
sure i will have a look. i also noticed some CTD problem but didnt think of memory leak.



---Original---
From: ***@***.***&gt;
Date: Mon, May 2, 2022 18:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [derekhe/msfs2020-map-enhancement] Severe memory leak—caused by Python instance on version 5.0.0 beta—leads to heavy performance loss and game crash (Issue #128)




 
On the version 5,0.0 beta release, there is a severe memory leak with the Python instance. I recently installed the update from the flightsim.to website and upon loading the program with the simulator, the Python instance's memory usage went skyrocketing.
 
This issue has caused the simulator to suffer heavy performance losses (via stuttering) and eventually crash the program due to an out-of-memory error. The leak will always occur regardless of how I start the newest version of the program.

**Comment by derekhe** [comment]
I had checked there is no memory leak. I also experience CTD problem but I noticed it is not caused by this mod.

**Comment by Tinh1000000** [comment]
Seems like the latest update (5.0.1) has fixed this issue, at least on my end. Thank you very much for looking into it!
