### ISSUE TITLE
Erro26 SQLite on startup

### ISSUE THREAD

**Issue by Maverick060817** [derekhe/msfs2020-map-enhancement#267]
Good day since I have updated to version 6.1.8 I get SQLite error on start up, error code 26.

I use Microsoft fs2020 MS version.

it was working fine prior last update.

please advise.

thanks.

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by SimPilotAdamT** [comment]
I also have the issue but since your didn't actually provide anything useful @derekhe can use, I will provide it, using info from my own system

MSFS version:

Steam, SU10, exe version 1.27.21.0

Mod version: 6.1.8

Device ID: 857ACETRPK9XBN017JHV8NWXD4MAJPPPMP55HPPBBW9G038KV4G0

[log](https://github.com/derekhe/msfs2020-map-enhancement/files/9711109/log.zip)

Screenshots:

![image](https://user-images.githubusercontent.com/71192298/193936757-ec007e8c-0216-479e-9bb3-5ac3f2edb0f5.png)
![image](https://user-images.githubusercontent.com/71192298/193936778-8dd485a7-83c8-4e01-a36b-cd51d6600b24.png)
![image](https://user-images.githubusercontent.com/71192298/193936844-2256fa7b-e4e1-4d1c-b6ec-5019d9d69354.png)
![image](https://user-images.githubusercontent.com/71192298/193936875-2c546722-4749-4fc1-b364-24e82a78b3c4.png)

Additional context (may not apply to @Maverick060817's system):
I run Windows 11 from the Dev branch of the Windows Insider program. Currently that is build 25206 on my machine as of 2022-10-04T21:52Z. My internet connection is no issue here, I have gigabit speeds.

**Comment by DavidT811** [comment]
I had the same issue. Running the uninstaller then reinstalling fixed the issue. Try that

**Comment by derekhe** [comment]
Sorry this issue is caused by upgrade of cache file format. Please delete the cache file manually and try again.

You can try

* Uninstall the old version and empty the installation directory. Reinstall 6.1.8. If it works fine, it's fine.
* In the Setting screen, if you turn on Cache Enabled and specify another cache.db path, please find this file and just delete it manually.

**Comment by Maverick060817** [comment]
Please apologies for my incompleted informations.

I’ll follo your issue since my set up is the same!

Cheers

**Comment by SimPilotAdamT** [comment]
> Sorry this issue is caused by upgrade of cache file format. Please delete the cache file manually and try again.
> 
> You can try
> 
>     * Uninstall the old version and empty the installation directory. Reinstall 6.1.8. If it works fine, it's fine.
> 
>     * In the Setting screen, if you turn on Cache Enabled and specify another cache.db path, please find this file and just delete it manually.

Yep that worked, thanks. (@Maverick060817 just do what he said)
