### ISSUE TITLE
Cant Load the mod any longer

### ISSUE THREAD

**Issue by Topher420247** [derekhe/msfs2020-map-enhancement#349]
Anytime i try to load any of the servers i get the check proxy error. used to work and loved using the apple map for most of the alps but havent been able to use it here lately. i tried uninstalling and reinstalling but nothing changed still have the same issue.

Latest update msstore

7.1.0 pro

**Device ID**
- Device ID QZ7BRNX5MRGW1HHYRNHE5ZSM3GYGW2EKY3NESXD5FYPTR08PVHG0
- 
[nlog-internal.log](https://github.com/derekhe/msfs2020-map-enhancement/files/11067900/nlog-internal.log)

**Comment by vrivoire** [comment]
Same here

**Comment by calizan** [comment]
same here

**Comment by sn007b9368** [comment]
I get 'Backend server start failed' for pretty much any map server I try. I can get it to start on Google Map Server 2 (Pro) when I refresh with Ctrl + R. I'm using 7.1.1 Pro.

**Comment by ehtripleseven** [comment]
same here.. any soluction?

**Comment by ehtripleseven** [comment]
> how about 7.1.2?

I have already tested all the last three versions available here and still the Proxy error continues

**Comment by derekhe** [comment]
Please give me the device id in license page

**Comment by derekhe** [comment]
@ehtripleseven I checked your app should be working good. Could you give me the screenshot?

**Comment by ehtripleseven** [comment]
> @ehtripleseven I checked your app should be working good. Could you give me the screenshot?

Working fine now, very thanks!!

**Comment by Brandon97400** [comment]
Hello guys, 

I have the same problem. 
The application crash after more 5h games (only via server Google Maps). 
The Bing Server work fine but i would like Google Maps. 
I have no solution , i have all try. 

DevideId: 78NF2YCPBA9CGX61ZYJGWTXB8VQJ2Q22Y6YH0QXB9HECSYVSEZE0

Error Message: Image server test failed

Can't access remote image server

If you are using a proxy to connect to remote server, please make sure the proxy is working.

**Comment by Topher420247** [comment]
Same thing i just updated and i just get the proxy error every time i try to start the server
QZ7BRNX5MRGW1HHYRNHE5ZSM3GYGW2EKY3NESXD5FYPTR08PVHG0

**Comment by derekhe** [comment]
If you are using google server, then it maybe blocked by Google maps (the threshold value var from different location)

**Comment by Topher420247** [comment]
> If you are using google server, then it maybe blocked by Google maps (the threshold value var from different location)

i checked and can still load google maps thru the website i also just updated to the newest .5 version and i still have the same issue cant connect to anything but apple and when i go into the game it doesnt actually load the apple map it just loads like the planet core but not the high detail map that goes on top of it. ill go in and remove everthing and start from scratch appdata and folder data for the mod and reinstall everything and it still has the same issue

**Comment by Gord21731** [comment]
Здравствуйте! Такая проблема возникла два дня назад! До этого времени все работало идеально! Когда вы начинаете загружать карты Art GIS, вы видите окно с текстом:
Сбой теста сервера изображений

Не удается получить доступ к удаленному серверу изображений

Если вы используете Google Maps, пожалуйста, убедитесь, что вы можете открыть https://www.google.com/maps в вашем браузере. Google может заблокировать вас из-за большого количества запросов.
Если вы используете прокси для подключения к удаленному серверу, пожалуйста, убедитесь, что прокси работает.
Пожалуйста, также посетите страницу часто задаваемых вопросов для получения дополнительной информации.
Можете ли вы сказать мне, в чем проблема и как ее решить, или ведется работа по решению этой проблемы?
Идентификатор устройства: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G

**Comment by Gord21731** [comment]
Здравствуйте! Такая проблема возникла два дня назад! До этого времени все работало идеально! Когда вы начинаете загружать карты Art GIS, вы видите окно с текстом:
Сбой теста сервера изображений

Не удается получить доступ к удаленному серверу изображений

Если вы используете Google Maps, пожалуйста, убедитесь, что вы можете открыть https://www.google.com/maps в вашем браузере. Google может заблокировать вас из-за большого количества запросов.
Если вы используете прокси для подключения к удаленному серверу, пожалуйста, убедитесь, что прокси работает.
Пожалуйста, также посетите страницу часто задаваемых вопросов для получения дополнительной информации.
Можете ли вы сказать мне, в чем проблема и как ее решить, или ведется работа по решению этой проблемы?
Идентификатор устройства: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G
Hello! Such a problem arose two days ago! Up to this time everything worked perfectly! When you start downloading Art GIS maps, you see a window with the text:
Image Server Test failed

Unable to access remote image server

If you use Google Maps, please make sure you can open https://www.google.com/maps in your browser. Google may block you due to a large number of requests.
If you are using a proxy to connect to a remote server, please make sure that the proxy is working.
Please also visit the FAQ page for more information.
Can you tell me what the problem is and how to solve it, or is work underway to solve this problem?
Device ID: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G

**Comment by Gord21731** [comment]
Hello! Such a problem arose two days ago! Up to this time everything worked perfectly! When you start downloading Art GIS maps, you see a window with the text:
Image Server Test failed

Unable to access remote image server

If you use Google Maps, please make sure you can open https://www.google.com/maps in your browser. Google may block you due to a large number of requests.
If you are using a proxy to connect to a remote server, please make sure that the proxy is working.
Please also visit the FAQ page for more information.
Can you tell me what the problem is and how to solve it, or is work underway to solve this problem?
Device ID: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G
