### ISSUE TITLE
Backend Server start failed

### ISSUE THREAD

**Issue by derekhe** [derekhe/msfs2020-map-enhancement#409]
### Discussed in https://github.com/derekhe/msfs2020-map-enhancement/discussions/408

<div type='discussions-op-text'>

<sup>Originally posted by **Laguiole** June  3, 2023</sup>
Hello everyone,

I would need your help because I've tried everything and I'm out of solutions. I can't launch the software.

I opened it in admin mode, checked that the ports weren't being used, reinstalled the software multiple times, checked if there was a WMI issue... in short, I'm out of ideas.

Thank you very much for your support.</div>

**Comment by derekhe** [comment]
What's your device id?

**Comment by Gord21731** [comment]
Здравствуйте! Возникла такая проблема два дня назад! До этого времени все работало отлично! При запуске подгрузки карт Art GIS вы ходит окно с текстом:
Image server test failed

Unable to access remote image server

If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.
If you are using a proxy to connect to the remote server, please ensure that the proxy is working.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.
Подскажите в чем проблема и как ее решить или ведутся работы по решению этой проблемы?

**Comment by Gord21731** [comment]
Здравствуйте! Возникла такая проблема два дня назад! До этого времени все работало отлично! При запуске подгрузки карт Art GIS вы ходит окно с текстом:
Image server test failed

Не удается получить доступ к удаленному серверу изображений

Если вы используете Google Maps, пожалуйста, убедитесь, что вы можете открыть https://www.google.com/maps в вашем браузере. Google может заблокировать вас из-за большого количества запросов.
Если вы используете прокси для подключения к удаленному серверу, пожалуйста, убедитесь, что прокси работает.
Пожалуйста, также посетите страницу часто задаваемых вопросов для получения дополнительной информации.
Подскажите в чем проблема и как ее решить или ведутся работы по решению этой проблемы?
Hello! There was such a problem two days ago! Up to this time everything worked perfectly! When you start loading Art GIS maps, you see a window with the text:
Image server test failed

Unable to access remote image server

If you are using Google Maps, please make sure that you can open https://www.google.com/maps in your browser. Google may block you due to a large number of requests.
If you are using a proxy to connect to a remote server, please make sure that the proxy is working.
Please also visit the FAQ page for more information.
Can you tell me what the problem is and how to solve it, or is work underway to solve this problem?

**Comment by Gord21731** [comment]
Hello! There was such a problem two days ago! Up to this time everything worked perfectly! When you start loading Art GIS maps, you see a window with the text:
Image server test failed

Unable to access remote image server

If you are using Google Maps, please make sure that you can open https://www.google.com/maps in your browser. Google may block you due to a large number of requests.
If you are using a proxy to connect to a remote server, please make sure that the proxy is working.
Please also visit the FAQ page for more information.
Can you tell me what the problem is and how to solve it, or is work underway to solve this problem?

**Comment by Gord21731** [comment]
DeviceID: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G
