### ISSUE TITLE
[Feature] using images from same zoom level at all distances

### ISSUE THREAD

**Issue by mikluhomaklay** [derekhe/msfs2020-map-enhancement#457]
#### Motivation

There is a problem with all map providers including MapBox, Apple and Bing. Tiles from different zoom levels are not necessarily matching in certain areas. For instance they may use sat images from different seasons for different zoom levels. This results in extremely annoying sharp blending. At close distance around the airplane it may load higher resolution tiles which were taken in spring, while a little further away it suddenly switches to tiles from another zoom level which may be from autumn. Then you see a kind of circle around your plane with brighter or darker tiles then what is outside of this circle. You clearly see that border especially when flying over fields. The circle is following the plane so it switches back to tiles of different color behind the plane. 

#### Detailed design

A possible solution to counter this issue might be to (optionally) enforce always using tiles from same (highest) zoom level. 
The lower resolution images that the sim is using for distant tiles (outside of high resolution circle) might not be requested from the service directly with a lower zoom level parameter. But instead it could request the image in the high resolution and then downsample it to fit into what ever the sim requires. 

This however would certainly result in much higher bandwidth requirements as the image-server would have to request high resolution for all tiles, including those in the far distance. However most users should have enough bandwidth available to handle it. 
Speaking for myself, im using a 500 Mbit line, which is utilized by maybe only 5% at most right now with highLOD setting enabled. I wouldn't mind to have to download more. In europe and other developed countries 500 Mbit is about standard, many having even more then that. For those who struggle with the lower bandwidth, this option could be optional just like the highLOD setting. 

#### Alternatives

Don't see an alternative solution for the described issue but maybe switching to a different provider and hoping that it has matching tiles in that particular area. But from my experience the affected areas are often causing that issue with all map providers as they often use same images.

**Comment by derekhe** [comment]
Yes, I tried this in very early stage, and it doesn't work actually because it needs too many tiles to be loaded. When we are flying high, the tiles loaded are in level 12 or 13. If we load level 18 or 19 （which normally have different tiles compare to above）, instead of loading 1 level 12 image, it needs to load 4^(18-12) = 4096 images and then merge then together and resize them. Currently if it loads 200 images/sec at max in a good network, it needs at least 20 sec to finish （which may trigger timeout in msfs2020）. And the 4096 images needs to resize and merge which cause huge CPU load.

One possible solution may offline load these images and do offline process first.
Another solution would be just don't load the detailed layers.

**Comment by Tirroto** [comment]
Hello,
Yes very good idea. I would like too see this kind of fonction, the changing tiles is very annoying on low altitude.
Not load the detailed tiles could be a good alternative I think, to not charge CPU and avoid popping tiles
