### ISSUE TITLE
Darker Tiles/Obvious Lines on Google servers

### ISSUE THREAD

**Issue by SilveraElenin** [derekhe/msfs2020-map-enhancement#46]
**Describe the bug**
Obvious darker lines between tiles.

![loww googlemaps](https://user-images.githubusercontent.com/98715161/151719284-526a6600-3eb0-441e-a016-6437d63d229e.jpg)

 MSFS2020 store version.

Is this fixable somehow? I am on mt google server.

**Comment by derekhe** [comment]
If you see this on google earth, then I can't fix it. Please confirm it.

**Comment by SilveraElenin** [comment]
![lowwearth](https://user-images.githubusercontent.com/98715161/151767204-ff9288a5-fe83-48ba-8b74-3ccf9652d659.jpg)

No such thing on google earth as can be seen above.

**Comment by derekhe** [comment]
That may caused by different LOD's image. I see this area contains photogrammetry data from Google. The photogrammetry tiles are very bright compare to others. You can check London city:

![image](https://user-images.githubusercontent.com/1734077/152987388-95d475f5-1dcb-4b82-860a-86c9b2aa5967.png)

[https://earth.google.com/web/search/London,+%e8%8b%b1%e5%9b%bd/@51.64384336,-0.4640728,49.75480005a,781.7830223d,35y,-17.59157136h,64.56348467t,0r/data=CnkaTxJJCiUweDQ3ZDhhMDBiYWYyMWRlNzU6MHg1Mjk2M2E1YWRkZDUyYTk5GXt5S4PswElAIYzgNZ6-VMC_Kg5Mb25kb24sIOiLseWbvRgBIAEiJgokCYcHHCyy7UDAEZWxq-zd7kDAGa0XAZME52JAIbpXjjCU5mJA](url)

Please check and if you still have trouble, give me the longtitude and latitude.
