### ISSUE TITLE
No satellite images loading

### ISSUE THREAD

**Issue by Amorisia** [derekhe/msfs2020-map-enhancement#495]
**Describe the bug**
Hello,

As I am in China I always used the mod with my Astrill VPN, so I always let the proxy option blank. Today (did not use the mod for about 1 month), I started the mod using 7.3.4 first. For all servers I can connect without any issue and it loads first 8 images (on highLOD) or first 2 images with highLOD only when flying activated). 

I checked the  host file and it has been modified as it should.

But in the sim it does not load any image. I tried with cache on and off and on several locations (SSD HDD etc0 and this is still the same. For information, cache third line always mention "calculating..." even if disabled.

I then tried with 7.4.1beta, result is the same. as it is a beta I then downgraded to 7.4.0 where issue is the same also.

Any advice ? I attached log file if needed.

Thank you agin for your time and devotion for the simmers community,

Chris

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.34.16.0

**Mod version:**
- 7.3.4, 7.4.0 and 7.4.1 beta

**Device ID**
- 1DCTED9P942F24XNSX2MSKQNC9KM7K4WKPBYNC4AA3XSWGVV7HA0

**Screenshots**

![map enhancement 7 4 0](https://github.com/derekhe/msfs2020-map-enhancement/assets/3002706/2c63ee4b-85d5-4155-9330-aef883ddb8ec)

![options](https://github.com/derekhe/msfs2020-map-enhancement/assets/3002706/9c4223a6-d004-4435-abb0-50aab2501009)

[log20231116.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/13371636/log20231116.txt)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I see the same problem today. It was good yesterday, I will investigate&nbsp;





------------------ Original ------------------
From: Amorisia ***@***.***&gt;
Date: Thu,Nov 16,2023 10:40 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] No satellite images loading (Issue#495)





 
Describe the bug
 Hello,
 
As I am in China I always used the mod with my Astrill VPN, so I always let the proxy option blank. Today (did not use the mod for about 1 month), I started the mod using 7.3.4 first. For all servers I can connect without any issue and it loads first 8 images (on highLOD) or first 2 images with highLOD only when flying activated).
 
I checked the  host file and it has been modified as it should.
 
But in the sim it does not load any image. I tried with cache on and off and on several locations (SSD HDD etc0 and this is still the same. For information, cache third line always mention "calculating..." even if disabled.
 
I then tried with 7.4.1beta, result is the same. as it is a beta I then downgraded to 7.4.0 where issue is the same also.
 
Any advice ? I attached log file if needed.
 
Thank you agin for your time and devotion for the simmers community,
 
Chris
 
MSFS version:
  
msstore
 
MSFS2020 Version 1.34.16.0
  
Mod version:
  
7.3.4, 7.4.0 and 7.4.1 beta
  
Device ID
  
1DCTED9P942F24XNSX2MSKQNC9KM7K4WKPBYNC4AA3XSWGVV7HA0
  
Screenshots
 

 

 
log20231116.txt
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.

**Comment by Amorisia** [comment]
Thank you for your quick answer. for information, even with cache disabled I get continuesly cache calculation lines in the log file.

2023-11-16 10:42:26.526 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:42:36.535 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:42:46.537 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:42:56.531 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:43:06.528 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:43:16.532 +08:00 [INF] Cache average time: Get 0 ms, Put 0
2023-11-16 10:43:24.782 +08:00 [INF] Cache size: -1 bytes
2023-11-16 10:43:24.783 +08:00 [INF] Calculate db size took 0 ms

**Comment by derekhe** [comment]
It is MSFS's issue. I tested without my mod the original image doesn't work.

https://forums.flightsimulator.com/t/bing-data-streaming-issues-nov-23/616901

https://forums.flightsimulator.com/t/bing-maps-outage-2023-11-15/616905

**Comment by Vitold69** [comment]
Arc GIS maps don't work as well!

**Comment by derekhe** [comment]
Yes, non of the maps works because if you go back to original map, it doesn't work as well.
Please wait for the msfs fix the issue and then it should be ok.

**Comment by derekhe** [comment]
Please use latest 7.4.3
