### ISSUE TITLE
Backend Server Issue Still Not Resolved

### ISSUE THREAD

**Issue by matthewvh** [derekhe/msfs2020-map-enhancement#516]
My last bug case, case #510, was closed even though it was not resolved.  I am reposting it

Please describe the bug in detail to help me understand the scenario

MSFS version:

    steam
    1.34.16.0

Mod version:

    7.4.5 beta

Device ID

    CVMXT3QMBPWV1JJZCXJ06MQP2DZX89DW77KYXXFTBR1FG2WY6CQ0

![285600504-6d783832-7ed3-4d05-a654-a19809d00944](https://github.com/derekhe/msfs2020-map-enhancement/assets/97539790/e4201504-babb-4b34-9e3f-0946de7dd99d)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
For this issue I have no idea. Please refer to the English manual and check if there are something can help you.&nbsp;





------------------ Original ------------------
From: matthewvh ***@***.***&gt;
Date: Sun,Dec 10,2023 2:49 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Backend Server Issue Still NotResolved (Issue #516)





 
My last bug case, case #510, was closed even though it was not resolved.  I am reposting it
 
Please describe the bug in detail to help me understand the scenario
 
MSFS version:
 steam 1.34.16.0  
Mod version:
 7.4.5 beta  
Device ID
 CVMXT3QMBPWV1JJZCXJ06MQP2DZX89DW77KYXXFTBR1FG2WY6CQ0  
285600504-6d783832-7ed3-4d05-a654-a19809d00944.png (view on web)
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#65-virus-report-and-https-certificate-error
