### ISSUE TITLE
Tiles Popping Up In Distance

### ISSUE THREAD

**Issue by SilveraElenin** [derekhe/msfs2020-map-enhancement#53]
**Describe the bug**
The tiles on the ground is loading/popping up when you get closer or in the distance and it is so obvious that breaks the whole sim experience. I happens mostly after 1500ft AGL get more visible at higher levels of flight. Both Mod cache and in game cache was disabled during my tests to check if it was about the caching but obviously not.

**Screenshots**
I have added a video to describe the problem. You should especially check the part starting after 30sec of the video. Link: https://youtu.be/U4iY59t0DJE

**Desktop (please complete the following information):**
 - MSFS2020 store version

**Comment by derekhe** [comment]
Thanks for this video. I noticed this very early and still working on to fix it.
The problem is that different LOD layer has different brightness. In google map's case, higher LOD sometimes has darker images, so when game load the higher LOD, it shows dark tiles.

The way MSFS2020 to fix it is to do a color correction, so that different layer has same brightness. I have done some similar try but it will make the image green (same as MSFS2020's bing map's situation). I'm trying other ways to fix it.

Please stay tunned.
