### ISSUE TITLE
MSFS2020 MAP ENHANCEMENT

### ISSUE THREAD

**Issue by baar78** [derekhe/msfs2020-map-enhancement#539]
**Describe the bug**
too old version
Please describe the bug in detail to help me understand the scenario
I downloaded the lastest version  7.4.6.pro and it says it is un old version
**MSFS version:**
store version msfs2020
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provi
![Capture d'écran 2024-01-03 144224](https://github.com/derekhe/msfs2020-map-enhancement/assets/60548816/be849e43-c0ad-43e7-bd2d-49788036a543)
de me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by KolosovV** [comment]
Last version is 7.5.2. You can download it via Releases here on GitHub and update.

**Comment by alanbeasy** [comment]
It would be nice to have a link in the App itself to download and install the latest update if possible.

**Comment by derekhe** [comment]
Yes, I will do it. Sorry for the inconvenience.

**Comment by alanbeasy** [comment]
Thanks for the good work.  Flew all day today with version 7.5.2 with zero errors on loading tiles.  It was a nice clean run with no glitches.

**Comment by alanbeasy** [comment]
Hi Derek.  I had to do a System Restore of my computer since the last Map Enhancement update 7.5.9
When I try to open I get this message
![Screenshot 2024-03-18 165147](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/1aaeeffa-4f3e-43ad-9701-19c33159dd5b)
I have done 1, 3 and 4.
How do I do number 2... and what will it do?
![Screenshot 2024-03-18 170900](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/3fb4e398-38e9-4441-b4b0-25139f55f866)

What is the Error: Reached max retry
