### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by dsweingard** [derekhe/msfs2020-map-enhancement#545]
The FAQ does not say how to uninstall this mod.  Is it a simple delete the folder it puts in the default install directory or is there some other process?  Feels like you should be explaining somewhere what the procedure is for uninstall.  The FlightSim.to page does not contain any instructions either.  

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
You can uninstall it in the add/remove applications, same as other apps&nbsp;





------------------ Original ------------------
From: dsweingard ***@***.***&gt;
Date: Thu,Jan 4,2024 11:13 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Uninstall (Issue #545)





 
The FAQ does not say how to uninstall this mod.  Is it a simple delete the folder it puts in the default install directory or is there some other process?  Feels like you should be explaining somewhere what the procedure is for uninstall.  The FlightSim.to page does not contain any instructions either.
 
Please describe the bug in detail to help me understand the scenario
 
MSFS version:
  
msstore or steam
 
MSFS2020 Version [e.g. 22]
  
Mod version:
  
Mod version
  
Device ID
  
Device ID
  
Screenshots
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.

**Comment by dsweingard** [comment]
Thank you. 


Sent from Yahoo Mail for iPhone


On Thursday, January 4, 2024, 7:20 AM, hesicong ***@***.***> wrote:



You can uninstall it in the add/remove applications, same as other apps&nbsp;





------------------ Original ------------------
From: dsweingard ***@***.***&gt;
Date: Thu,Jan 4,2024 11:13 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Uninstall (Issue #545)





 
The FAQ does not say how to uninstall this mod. Is it a simple delete the folder it puts in the default install directory or is there some other process? Feels like you should be explaining somewhere what the procedure is for uninstall. The FlightSim.to page does not contain any instructions either.
 
Please describe the bug in detail to help me understand the scenario
 
MSFS version:
 
msstore or steam
 
MSFS2020 Version [e.g. 22]
 
Mod version:
 
Mod version
 
Device ID
 
Device ID
 
Screenshots
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.

**Comment by gadjou** [comment]
Pay attention when removing it this way, msfs2020-map-enhancement modifies your hosts file (C:\Windows\System32\drivers\etc\host). You will need to edit it manually, else you won't be able to use online bing data anymore from msfs.
