### ISSUE TITLE
Device blocked

### ISSUE THREAD

**Issue by GAE074** [derekhe/msfs2020-map-enhancement#552]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

Since yesterday I get the message: "This device is blocked and this usually means your payment is invalid. If you think this is a mistake, please contact the author."

My subscription is 365 days and started at 15th Febuary 2023, so it is still valid. I already send an email to hesicong@gmail.com yesterday, but did not got any answer.

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version: 7.5.3

**Device ID**
- Device ID: T0ASSN93F3RKG7M9P9M011ZCWNT58F5WBBJ4N8ZXVKH7Z927M7P0

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/79332639/2396161e-4428-4b5f-84af-1b38bb04a8fa)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
That's because you requested a new license with payment channel buymeacoffee at 2nd Jan. This information is not correct. Did you lost your license file and want a new one?
If yes, then you should go to key.aiflygo.com and request a refresh license there (the second option).
I unblocked it for you now and please don’t use the license you requested recently.

**Comment by GAE074** [comment]
I did not requested a new licence, will test, if it works with the old one and let you know.

**Comment by derekhe** [comment]
ok doesn’t matter





------------------ Original ------------------
From: GAE074 ***@***.***&gt;
Date: Mon,Jan 8,2024 3:17 PM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Device blocked (Issue #552)





 
It works again! To be clear, I did literally nothing, not changing anything, not requesting a new licence. The only thing, I could imagine is, because I opened a bug ticket here in github (#529) and had to put in my device ID, could it be, that someone took the device ID from the ticket and requested a new licence?
