### ISSUE TITLE
In flight - Errors ? 

### ISSUE THREAD

**Issue by paulwain** [derekhe/msfs2020-map-enhancement#596]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Describe the bug**

Can anyone point me in the right direction,( I have read the manual) but not sure if i have missed something....

When in flight at the start everything runs fine but then  I always have errors maybe within 1-2hrs of a flight, and the textures go blurry so I assume its not pulling in the images. ( See image below ) I have been a pro member for a while and haven't had this issue before so not sure if its a temporary  thing or something on my end.  I dont need or use a proxy and Google maps work fine on the internet. 

- I have uninstalled and reinstalled 
- Tried google and bing map (same issue for both) 
- Deleted Cache - Within the app and in MFS ( even though this is turned off within mfs) 
-  Is online mode
- Bing and Photogrammetry ON 
-  Network is on NORMAL mode
- Deleted HOSTS file

**Map Enhancement version:**
- 7.5.9 Pro

**Device ID**
H4GB70XP5HZTAD1EPBXVJ6S8NMNQVGYRC46AR327ZJ0AVXWGJWYG

**Screenshots**
![IMG_5670](https://github.com/derekhe/msfs2020-map-enhancement/assets/155645900/de2698bb-a752-4a6a-946a-d59306e8fceb)

**Comment by derekhe** [comment]
This is because google blocks you because of large access of the servers. You can switch to other servers to have a try.





------------------ Original ------------------
From: paulwain ***@***.***&gt;
Date: Tue,Mar 26,2024 11:20 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] In flight - Errors ?  (Issue #596)





 
Before you raise a bug
 
[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
 
Describe the bug
 
Can anyone point me in the right direction,( I have read the manual) but not sure if i have missed something....
 When in flight I always have errors starting maybe within 1-2hrs of a flight, and the textures go blurry so I assume its not pulling in the images. ( See image below ) I have been a pro member for a while and haven't had this issue before so not sure if its a temporary  thing or something on my end.
  
I have uninstalled and reinstalled
 
Tried google and bing map (same issue for both)
 
Deleted Cache - Within the app and in MFS ( even though this is turned off within mfs)
 
Network is on NORMAL mode
 
Deleted HOSTS file
  
Map Enhancement version:
  
7.5.9 Pro
  
Device ID
 H4GB70XP5HZTAD1EPBXVJ6S8NMNQVGYRC46AR327ZJ0AVXWGJWYG
 
Screenshots
 IMG_5670.jpg (view on web)
 
Please provide me screenshots for the mod and msfs2020 if possible

**Comment by paulwain** [comment]
> This is because google blocks you because of large access of the servers. You can switch to other servers to have a try.
> […](#)
> ------------------ Original ------------------ From: paulwain ***@***.***&gt; Date: Tue,Mar 26,2024 11:20 PM To: derekhe/msfs2020-map-enhancement ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] In flight - Errors ? (Issue #596) Before you raise a bug [] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN Describe the bug Can anyone point me in the right direction,( I have read the manual) but not sure if i have missed something.... When in flight I always have errors starting maybe within 1-2hrs of a flight, and the textures go blurry so I assume its not pulling in the images. ( See image below ) I have been a pro member for a while and haven't had this issue before so not sure if its a temporary thing or something on my end. I have uninstalled and reinstalled Tried google and bing map (same issue for both) Deleted Cache - Within the app and in MFS ( even though this is turned off within mfs) Network is on NORMAL mode Deleted HOSTS file Map Enhancement version: 7.5.9 Pro Device ID H4GB70XP5HZTAD1EPBXVJ6S8NMNQVGYRC46AR327ZJ0AVXWGJWYG Screenshots IMG_5670.jpg (view on web) Please provide me screenshots for the mod and msfs2020 if possible — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

You cant switch servers in flight though, so if i'm in middle of a flight, basically I wont be seeing any scenery : /

Didn't realise there were limits with using the google mod :/ .... i guess its one of those things but safer option is to use default bing maps :/

**Comment by derekhe** [comment]
You can switch server at any time and it will continue to load from new server&nbsp;





------------------ Original ------------------
From: paulwain ***@***.***&gt;
Date: Wed,Mar 27,2024 0:53 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] In flight - Errors ?  (Issue#596)





 
You cant switch servers in flight though, so if i'm in middle of a flight, basically I wont be seeing any scenery : /
 
Didn't realise there were limits with using the google mod :/ .... i guess its one of those things but safer option is to use default bing maps :/

**Comment by derekhe** [comment]
Another way is that you can switch to google maps server 2

paulwain ***@***.***>于2024年3月27日 周三00:53写道：

**Comment by paulwain** [comment]
Oh I didnt know I could change the server once in flight - I thought once I pressed start I wasnt be able to change. 

I will test it out if I receive errors and let you know.

I have been using server 2 today - no issues
