### ISSUE TITLE
Maps LOWW Error 

### ISSUE THREAD

**Issue by Marius234987** [derekhe/msfs2020-map-enhancement#599]
**Good day, long known problem since 2023. I don't know why fixing it doesn't do anything and hopefully they will investigate the fix next update please. Many thanks Best regards Marius KY
-------------------------------------------------------------------------------------------------------
Steam: MSFS2020 
Apple Map (Pro)
7.5.11 (Pro)
Device ID 26XX376JK4DFR4WE0SE205EHNHYQPECMXM7ZZJ67G8SBN6CKW2A0
![1](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/aa048c65-ec7c-4594-b11a-ac894883a223)
![2](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/096c1729-2f62-47cd-89d5-442a69c1e2ad)
![3](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/15953cef-e20e-45e8-a2c7-f15131eaa9ee)
![4](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/ab754a3d-151c-4a6e-af8f-4ecd39413e76)
![5](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/af6630c4-eb34-4958-ba9b-d47f08310256)

**Comment by AppleUK123** [comment]
Same here +1

**Comment by derekhe** [comment]
This is because of the photogrammetry data issue. I can't fix it.
When turn off the photogrammetry data it is good:
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/48b70fbc-b98e-49a3-96c9-c110c4e6ecdd)
If you turn on the photogrammetry data it looks like:
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/993aa419-94b4-4aa9-b587-589136d92d4e)
