### ISSUE TITLE
Very slow loading times and data connectivity problems when using the mod

### ISSUE THREAD

**Issue by siglr** [derekhe/msfs2020-map-enhancement#610]
Please describe the bug in detail to help me understand the scenario
Since just today (that I can recall), when the mod is running and started, I now have VERY long flight loading times, I mean easily 5 minutes to get to the cockpit. And, MSFS keeps disconnecting and reconnecting data, saying my bandwidth is not sufficient for streaming data. I've never had that before.

**Map Enhancement version:**
Version 7.5.15 Pro

**Device ID**
ZCBF7JHH1ZN89JMPW2JPG1DXW7B2N3KECD9V75KSK4M6XJDDJWEG

**Additional context**
When doing the same thing without the mod started, everything works fine in MSFS.

**Comment by derekhe** [comment]
It depends on the network situation a lot for msfs.





------------------ Original ------------------
From: Guy LaRochelle ***@***.***&gt;
Date: Tue,Apr 23,2024 9:26 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Very slow loading times and dataconnectivity problems when using the mod (Issue #610)





 
Please describe the bug in detail to help me understand the scenario
 Since just today (that I can recall), when the mod is running and started, I now have VERY long flight loading times, I mean easily 5 minutes to get to the cockpit. And, MSFS keeps disconnecting and reconnecting data, saying my bandwidth is not sufficient for streaming data. I've never had that before.
 
Map Enhancement version:
 Version 7.5.15 Pro
 
Device ID
 ZCBF7JHH1ZN89JMPW2JPG1DXW7B2N3KECD9V75KSK4M6XJDDJWEG
 
Additional context
 When doing the same thing without the mod started, everything works fine in MSFS.

**Comment by siglr** [comment]
But why only if the mod is started?

**Comment by derekhe** [comment]
You can try switch the network settings to normal and have a try





------------------ Original ------------------
From: Guy LaRochelle ***@***.***&gt;
Date: Tue,Apr 23,2024 10:50 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Very slow loading times anddata connectivity problems when using the mod (Issue #610)





 
But why only if the mod is started?

**Comment by siglr** [comment]
I think version 16 and 17 may have fixed the problems?

**Comment by siglr** [comment]
Yeah, it sure looks as fixed now.
