### ISSUE TITLE
Unable to patch hosts file issue:

### ISSUE THREAD

**Issue by biggles58** [derekhe/msfs2020-map-enhancement#630]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

downloaded the 7.6.0 version today May 31
Tried all I can see online for other peoples issues but I can`t see a remedy for this:

I get an error details : Access to path
C:\WINDOWS\system32\drivers\etc\hosts is denied

Any ideas?

**Comment by derekhe** [comment]
Please check the user manual&nbsp;





------------------ Original ------------------
From: biggles58 ***@***.***&gt;
Date: Sat,Jun 1,2024 3:24 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Unable to patch hosts file issue:(Issue #630)





 
Before you raise a bug
 
[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
 [] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/
 
Describe the bug
 
Please describe the bug in detail to help me understand the scenario
 
Map Enhancement version:
  
Map Enhancement version
  
Device ID
  
Device ID
  
Screenshots
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.
 
downloaded the 7.6.0 version today May 31
 Tried all I can see online for other peoples issues but I can`t see a remedy for this:
 
I get an error details : Access to path
 C:\WINDOWS\system32\drivers\etc\hosts is denied
 
Any ideas?
