### ISSUE TITLE
error base package folder 

### ISSUE THREAD

**Issue by marcog84** [derekhe/msfs2020-map-enhancement#722]
Hi, I have installed xplane ME v2.0.2 for win10, I set the base package folder in the settings menu (see screenshot), I have downloaded the packages of Africa automatically and the files VHD are correctly placed in the base package folder (see screenschot). But when I click on START an error appears and it says that at least one file VHD must be in the base packages folder. Actually the files VHD are there, so I don't know how it doest'n start.
I tried to modify folder position and SDD but no way to solve it.
Please, how can I solve this?

Thank you!

Marco
![base package folder](https://github.com/user-attachments/assets/3dfefeb6-0458-4beb-a3a7-ce073f3c19d1)
![error on start](https://github.com/user-attachments/assets/a78c5d60-100b-49cc-a694-47bfdaab22fe)
![setting base package path](https://github.com/user-attachments/assets/fba9825c-85d0-45c9-9ca8-3b8afa248145)

**Comment by derekhe** [comment]
Please follow the instructions: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN

**Comment by marcog84** [comment]
Actually I follow the instructions but that is the result

**Comment by derekhe** [comment]
You should click the exe file to merge the files into 1





------------------ Original ------------------
From: marcog84 ***@***.***&gt;
Date: Wed,Aug 21,2024 10:19 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] error base package folder (Issue #722)





 
Actually I follow the instructions but that is the result

**Comment by marcog84** [comment]
when I click on exe file an error says it was not set to work with the set the first piece file belongs to. It says also to use GUnite by gdgsoft, I tried it also but it does't work with the set of files.
![error on merging vhd files](https://github.com/user-attachments/assets/56a3fe5a-aa01-485b-bcec-e732f48d7c23)

**Comment by marcog84** [comment]
Actually I'm using the version 2.02 and already use the downloader inside the app. But after download an entire area, I can't start it because it says any VHD file is inside the vase package folder (the folder is set correctly on the setting page), and if I manually check the folder I see an exe file and 7 VHD files, if I click on exe file to merge them, it says it was not able to work with the set the first piece belongs to.

**Comment by derekhe** [comment]
Then you may have errors in the download or when merging. Please delete all files and redownload.





------------------ Original ------------------
From: marcog84 ***@***.***&gt;
Date: Thu,Aug 22,2024 0:10 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] error base package folder (Issue #722)





 
Actually I'm using the version 2.02 and already use the downloader inside the app. But after download an entire area, I can't start it because it says any VHD file is inside the vase package folder (the folder is set correctly on the setting page), and if I manually check the folder I see an exe file and 7 VHD files, if I click on exe file to merge them, it says it was not able to work with the set the first piece belongs to.
