### ISSUE TITLE
Bandwidth Issues Using Mod with Google Pro Server 2 (don't know about others)

### ISSUE THREAD

**Issue by EricFlight** [derekhe/msfs2020-map-enhancement#791]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - steam
 - MSFS2020 Version 1.38.2.0

**Mod version:**
- Mod version 8.0.27.0
**Device ID**
- Device ID NRFD3ZHV2RY47DE48AX9JNVXNJAY3G9FTJQDCMQA91RZH8A3H5Y0

**Screenshots**

MSFS2020 is randomly turning off photogrammetry again saying it's not downloading the scenery fast enough. My bandwidth is fine and I didn't have problems with this until recent versions (last 2-3). It was working fine before and used to do this a long time ago with the mod. I'm using Google Pro Server 2. The mod will work if I go to the option menus and reenable data but sometimes the imagery is blurry around the landing airport until after I land.

**Additional context**

**Comment by EricFlight** [comment]
See the following disonnects from my stream tonight:

1st time
https://www.youtube.com/live/Bd5oIkgoi30?si=zOcXgw7KWvkDgE6z&t=2625

2nd time
https://www.youtube.com/live/Bd5oIkgoi30?si=KfOxsRki8jlfrzR0&t=3168

Showing Map Enhancement the program as not responding (even though it still shows loading tiles) It eventually went back to a normal program about 5-10 minutes later
https://www.youtube.com/live/Bd5oIkgoi30?si=307f0hL3m4EjJ8Fj&t=6370


Scenery not loading as I get closer to 44N:
https://www.youtube.com/live/Bd5oIkgoi30?si=Qz4eMjXEj6gRSCMx&t=6496



I had to turn photogrammetry back on after getting kicked off both times. It is very infuriating especially when I am streaming live

It disconnected twice tonight and was very slow to load at my destination of 44N (it eventually loaded but was way after I landed)

**Comment by derekhe** [comment]
Hello,

Sorry for the inconvenience. I think the network issue may be caused by the application's slow response. But interesting it is still loading. I never had this problem or heard about this problem. My suggest is to look at how much CPU it is using and how much CPU you left. 

And another thing is the network issue, you know MSFS2024 has lots of network loads and it may cause issues for MSFS2020. (I don't have evidence, but this is my guess.)

Please keep monitoring. And you can also paste me the device id, I can look at the logs see if any clue.
