### ISSUE TITLE
MITM error on startup

### ISSUE THREAD

**Issue by ragamil** [derekhe/msfs2020-map-enhancement#802]
Before submit an issue, please have a look the user manual for FAQ: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Describe the bug**
Without notice, Map Enhancement fails to work as designed. 
After startup, and pressing "Start", the MITM error popup shows.

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
- steam
 - I have MSFS2020 and 2024, but error occurs before starting a flightsim

**Mod version:**
8.0.30.0 (I tried with earlier versions up tp 26, with the same result)

**Device ID**
YPDE9SDRJNKCPZS513HM9NVXT3YY7767D95XADXSAE98CY8E0170

**Screenshots**
please see below
Please provide me screenshots for the mod and msfs2020 if possible

![MSFSME01](https://github.com/user-attachments/assets/dbe46791-24ed-4241-8f45-7d1b306765e7)
![MSFSME02](https://github.com/user-attachments/assets/f60e00a7-72e4-4ded-bdc8-6f75b3d81cec)

**Additional context**
hosts file checked for read only (is not)
created new hosts file (no luck)
disabled both firewall and virusscanner (no luck, and worked fine previously)
system restore (not done yet, hoping for less drastic measure)
As I cannot find much info regarding this issue,it may well be a local issue, any help appreciated.

**Comment by derekhe** [comment]
I have no idea. All solutions I know has been updated on the wiki page now.

**Comment by ragamil** [comment]
Fair enough. I am also checking all wiki suggestions, and saw this phenomenon has been reported before. Unfortunately he did not mention whether/how he fixed it. 

Is it possible to provide me with a way that a debug log is produced?
Or can you give me a list of services on which MapEnhancement depends? That is something I can verify for myself.
Thanks in advance!

**Comment by derekhe** [comment]
The mod will check if accessing to MSFS original image server has change to go through this mod. e.g. Access to this url: https://khstorelive.azureedge.net/results/v1.20.0/coverage_maps/lod_8/12202100.cov?version=3 should return 404 other than 200.

**Comment by ragamil** [comment]
I pasted the URL (  ) into my browser. Instead of returning 404 or 200; it prompts me to save this file: 12202100.cov (111 bytes)

FYI, these lines are added to my hosts file:
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
127.0.0.1 cdn-shared-wca-endpoint.azureedge.net
127.0.0.1 sunriseworld.akamaized.net

**Comment by derekhe** [comment]
So this means the hosts override doesn’t work. It still goes to original website instead of goes to 127.0.0.1





------------------ Original ------------------
From: mnpostema32 ***@***.***&gt;
Date: Thu,Dec 19,2024 8:03 PM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] MITM error on startup (Issue#802)





 
I pasted the URL (  ) into my browser. Instead of returning 404 or 200; it prompts me to save this file: 12202100.cov (111 bytes)
 
FYI, these lines are added to my hosts file:
 127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
 127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
 127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
 127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
 127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
 127.0.0.1 khstorelive.azureedge.net
 127.0.0.1 cdn-shared-wca-endpoint.azureedge.net
 127.0.0.1 sunriseworld.akamaized.net

**Comment by ragamil** [comment]
Using another browser leads to a "Not Found" page.
But I am on to something: I had to log into my locat prtg server first. 
So I uninstalled PRTG. 

And (see pic): I can properly start MapEnhancement!

Will reboot ((because of deinstallation of PRTG) and check again. BRB

![image](https://github.com/user-attachments/assets/59d51caf-d11d-4eeb-b30d-b8e8062acbd1)

**Comment by derekhe** [comment]
Glad to hear. I think it is a VPN service to monitor all your traffic this why it won't work.

**Comment by ragamil** [comment]
I closed the issue as it has been resolved.
